### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by narnil** [CommunityHiQ/JefimsIncredibleXsltTool#1]
It would be easier on the eyes when mapping in a dark cave.

**Comment by jefim** [comment]
I have also thought about this and if I wasn't sick on the "do what you want" thing then it probably already be a reality :)

**Comment by narnil** [comment]
Color scheme could mimic Visual Studio or Visual Studio Code.

**Comment by jefim** [comment]
This is implemented in v1.12
